### ISSUE TITLE
Appender configuration and NPE

### ISSUE THREAD

**Issue by Gymondo-GmbH** [airbrake/log4javabrake2#3]
Hi,

I couldn't find any information on how to configure the account information so I assumed it would be like that

`
        <Airbrake name="Airbrake"
                  api_key="key"
                  env="test"
                  enabled="true"
                  url="https://api.airbrake.io/notifier_api/v2/notices"
                  async="true">
        </Airbrake>
        <Root level="warn">
            <AppenderRef ref="Airbrake"/>
        </Root>
`

But I can't get it work, besides that I get the following:
`
2018-04-18 16:43:39,116 localhost-startStop-1 ERROR An exception occurred processing Appender Airbrake java.lang.NullPointerException
        at io.airbrake.javabrake.Airbrake.send(Airbrake.java:18)
        at io.airbrake.log4javabrake2.AirbrakeAppender.append(AirbrakeAppender.java:41)
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
        at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:448)
        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:433)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:403)
        at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63)
        at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146)
        at org.jboss.logging.Log4j2Logger.doLogf(Log4j2Logger.java:66)
        at org.jboss.logging.Logger.logf(Logger.java:2414)
`

So what am I doing wrong and how to fix it? And where and how to configure the properties to connect to the proper airbrake account?

**Comment by vmihailenco** [comment]
Please try to upgrade and pass `projectId` and `projectKey` like this:

```
<Airbrake name="Airbrake" projectId="12345" projectKey="FIXME" env="production"></Airbrake>
```
